### ISSUE TITLE
pulsebot doesn't handle irc disconnection very well

### ISSUE THREAD

**Issue by glandium** [glandium/pulsebot#10]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/asynchat.py", line 110, in handle_read
    data = self.recv (self.ac_in_buffer_size)
  File "/home/ubuntu/bot/local/lib/python2.7/site-packages/sopel-6.3.1-py2.7.egg/sopel/irc.py", line 276, in _ssl_recv
    data = self.socket.read(buffer_size)
  File "/usr/lib/python2.7/ssl.py", line 260, in read
    return self._sslobj.read(len)
error: [Errno 104] Connection reset by peer

No handlers could be found for logger "sopel.modules.sopel.irc"
Calling shutdown for 0 modules.
Closed!
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/pulsebot/pulsebot/__main__.py", line 72, in <module>
    bot.shutdown()
  File "pulsebot/irc.py", line 92, in shutdown
    self._sopel.quit('Terminated')
AttributeError: 'NoneType' object has no attribute 'quit'
```

Then after that, it can't send messages anymore, and that breaks bugzilla updates as well, because all is chained. And since pulse messages are acknoledged immediately, they're also lost.

**Comment by glandium** [comment]
IRC support was removed in 3ab8e6dcf260727c7d392890cd61a9a69e0efc63
